title: Xinglong Liu
subtitle: State Key Lab of Virtual Realities and Systems
link: Homepage link
meta:
  description: Content of description meta tag
  keywords: !!seq
    - keyword1
    - keyword2
    - keyword3
  author: Content of author meta tag
master:
  name: Xinglong Liu
  about: Dr. of Computer Science, Beihang University
  email: liu3xing3long@163.com
rss:
  title: RSS feed title
  desc: RSS feed description
  lang: zh-cn
  max: 10
copyright:
  owner: Xinglong Liu
  beginYear: 2014
  endYear: 2017
  cpimage1: beihang.jpg
  cpimage2: vrlab.jpg
theme: default
codetheme: night